services:
  api:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - 8080:8080
    depends_on: db
    environment:
      RUST_BACKTRACE: full

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
